version: "3"
services:
  webapp:
    build:
      context: .
      no_cache: true
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge